# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d72a9a9b8d123f7873ef454664a5d18be47ec2e090f85fe14b99161e1f87b2d6510311bfbea56c0ca30537e151b9a07059c630bcc5e020c84465ec2c63d975ce

test:
  secret_key_base: 17de13e9013b1f7819640deea42ad0b693550a1170c4577db056d0e1614d2b205e7f9f3f7c24cbe03fde800fcb65c6a6645c5832d251448af9a976f23d9366ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
